---
global:
  writeToFile: false
  gc: {{.GC}}
  indexerConfig:
    enabled: {{.INDEXING}}
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: elastic
  measurements:
    - name: podLatency
      esIndex: {{.ES_INDEX}}
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: {{.POD_READY_THRESHOLD}}
jobs:
  - name: node-density
    namespace: node-density
    jobIterations: 1 
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: false
    podWait: true 
    jobPause: 600s 
    waitWhenFinished: true
    preLoadImages: false 
    #preLoadPeriod: 10s
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:

      - objectTemplate: pod.yml
        replicas: 50 
        inputVars:
          containerImage: ghcr.io/colinianking/stress-ng
